trigger:
  branches:
    include:
      - main

variables:
  - name: azureServiceConnection
    value: 'EAM-NonProd-SC' # example: replace with your Azure DevOps service connection name
  - name: resourceGroup
    value: 'network-zones-tst-yt-rg' # example: the networking non-prod resource group
  - name: appResourceGroup
    value: 'eam-app-tst-ae-rg'
  - name: location
    value: 'australiaeast'

- stage: Preflight
  displayName: Preflight: verify resource groups
  jobs:
    - job: CheckRGs
      displayName: 'Check resource groups exist'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: AzureCLI@2
        displayName: 'Verify required resource groups'
        inputs:
          azureSubscription: '$(azureServiceConnection)'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            set -euo pipefail
            echo "Checking resource groups..."
            for rg in '$(resourceGroup)' '$(appResourceGroup)'; do
              echo "Checking $rg"
              if ! az group show --name "$rg" >/dev/null 2>&1; then
                echo "Resource group $rg not found. Exiting."
                exit 1
              fi
            done
            echo "All resource groups exist."

stages:
- stage: Validate
  displayName: Validate Bicep (non-prod)
  jobs:
    - template: templates/validate-bicep.yml
      parameters:
        azureServiceConnection: '$(azureServiceConnection)'
        location: '$(location)'
        bicepFile: 'JHG/infrastructure/main.bicep'
        parametersFile: 'JHG/infrastructure/environments/non-prod/main.non-prod.bicepparam'

- stage: WhatIf
  displayName: WhatIf Bicep (non-prod)
  dependsOn: Validate
  jobs:
    - template: templates/whatif-bicep.yml
      parameters:
        azureServiceConnection: '$(azureServiceConnection)'
        location: '$(location)'
        bicepFile: 'JHG/infrastructure/main.bicep'
        parametersFile: 'JHG/infrastructure/environments/non-prod/main.non-prod.bicepparam'

- stage: Deploy
  displayName: Deploy Bicep (non-prod)
  dependsOn: WhatIf
  jobs:
    - template: templates/deploy-bicep.yml
      parameters:
        azureServiceConnection: '$(azureServiceConnection)'
        location: '$(location)'
        bicepFile: 'JHG/infrastructure/main.bicep'
        parametersFile: 'JHG/infrastructure/environments/non-prod/main.non-prod.bicepparam'
