parameters:
  - name: azureServiceConnection
    type: string

  - name: location
    type: string

  - name: parametersFile
    type: string


jobs:
- job: Validate
  displayName: 'Validate Subscription Deployment'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    displayName: 'Validate Bicep'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        echo "Building Bicep to verify syntax..."
        az bicep build --file JHG/infrastructure/main.bicep

        echo "Validating deployment (subscription scope)..."
        az deployment sub validate \
          --location "${{ parameters.location }}" \
          --parameters "${{ parameters.parametersFile }}"