parameters:
- name: azureServiceConnection
  type: string
- name: location
  type: string
- name: parametersFile
  type: string

jobs:
- job: Validate
  displayName: Validate Bicep
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    displayName: 'Validate Bicep using bicepparam'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        echo "Running subscription-level validation using bicepparam"

        az deployment sub validate \
          --location "${{ parameters.location }}" \
          --parameters "${{ parameters.parametersFile }}"