parameters:
- name: azureServiceConnection
  type: string
- name: location
  type: string
  default: 'australiaeast'
- name: parametersFile
  type: string

jobs:
- job: Validate
  displayName: Validate Bicep
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    displayName: 'Validate Bicep template (subscription)'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        echo "Validating deployment using bicepparam file"

        az deployment sub validate \
          --location "${{ parameters.location }}" \
          --parameters "${{ parameters.parametersFile }}"